### ISSUE TITLE
remove randomInt

### ISSUE THREAD

**Issue by v1rtl** [linostar/missing-in-node#1]
cuz there's `crypto.randomInt`

**Comment by linostar** [comment]
There is a difference between missing-in-node implementation of randomInt and crypto's implementation:

* missingInNode.randomInt: cryptographically insecure but very fast
* missingInNode.crypto.randomInt: cryptographically secure but much much slower

There are cases where each function is better suited, which makes more inclined to keep the second function in missing-in-node.

Thanks for your input!

**Comment by v1rtl** [comment]
ok thanks for explanation, closing this then
